---
apiVersion: v1
kind: Secret
metadata:
  name: merge-bot-secrets
stringData:
  github-access-token: ${GITHUB_ACCESS_TOKEN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: merge-bot-config
data:
  bot_config.yaml: |
    upstream: operator-framework/operator-sdk
    downstream: ${GH_USER}/${GH_REPO}
    overlay_branch: ${OVERLAY_BRANCH}
    log_level: ${LOGLEVEL}
    branches:
      master: master
      v0.12.x: release-4.3
      v0.11.x: release-4.2
    always_overlay:
      - master
    assignees: ${ASSIGNEES}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: merge-bot
spec:
  schedule: ${SCHEDULE}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: merge-bot
            image: ${IMAGE}
            volumeMounts:
            - name: bot-config
              mountPath: /config
            env:
            - name: MERGE_BOT_CONFIG
              value: /config/bot_config.yaml
            - name: GITHUB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: merge-bot-secrets
                  key: github-access-token
          volumes:
          - name: bot-config
            configMap:
              name: merge-bot-config
          restartPolicy: Never
          pullPolicy: Always
